USHORE=0
HLIMB=0
DCORE=0
BLIMB=0
MAXP0=0
MAXPK=0
SOUNDM=0
RLTANM=0
BTANKM=0
HTANKM=0
GTRPM=0
HLIMBM=0
DLMBMA=0
DLMBMI=0
NPHAS=0
FREQ=0
EVALP0=0
EVALPK=0
DPHAS=0
DPHSL=0
DWITA=0
DCOCOV=0
EXTANK=0
TWSUP=0
UMAXPU=0
QMONT=0
FONAN=0
TOPDTO=0
TTOILM=0
TWINDM=0
BLTOPM=0
HYOKAD=0
HYOKADM=0
UTURN=0
HLIMBN=0
LTANK=0
BTANK=0
HTANK=0

CURD0=[0 for i in range(9)]
MXCURD=[0 for i in range(9)]
ACOND0=[0 for i in range(9)]
PRESSM=[0 for i in range(9)]
TENSM=[0 for i in range(9)]

OPTTNK=''
CORESE=''
CKTANK=''
CORTYP=''
COREMA=''
BLDING=''
CVARN=''
KBAND=''
KCOOL=''
COEQIP=''
TYPREG=''
ETCPL=''
CONSP=''
SNDSCR=''
ALSHLD=''
T146AC=['' for i in range(2)]
REOPT=[['' for i in range(3)] for i in range(4)]
WNDOPT=['' for i in range(9)]
OLTC=''
LAYOUT=''
STEPLA=''

SRATE=[0 for i in range(9)]
UNLINE=[0 for i in range(9)]
NPSTEP=[0 for i in range(9)]
NMSTEP=[0 for i in range(9)]
PUSTEP=[0 for i in range(9)]
USURG=[0 for i in range(9)]
SLINE=[0 for i in range(9)]
XREA=[0 for i in range(4)]
DUYOKE=[0 for i in range(9)]
DLYOKE=[0 for i in range(9)]
BDUCT=[0 for i in range(9)]
NGROUP=[0 for i in range(9)]
FILLF=[0 for i in range(9)]
FRACT=[0 for i in range(9)]
BWIND=[0 for i in range(9)]
NCDUCT=[0 for i in range(9)]
XOILGR=[0 for i in range(9)]
XTRNAX=[0 for i in range(9)]
XTRNRD=[0 for i in range(9)]
XCBLAX=[0 for i in range(9)]
XCBLRD=[0 for i in range(9)]
XSTRAX=[0 for i in range(9)]
XSTRRD=[0 for i in range(9)]
HPART=[0 for i in range(9)]
BPART=[0 for i in range(9)]
COVSTR=[0 for i in range(9)]
COVCBL=[0 for i in range(9)]
CGRAD=[0 for i in range(9)]

TNODE=['' for i in range(9)]
KCON=['' for i in range(9)]
KTYPRW=['' for i in range(9)]
WNOD1=['' for i in range(9)]
WNOD2=['' for i in range(9)]
KWITYP=['' for i in range(9)]
KWIFUN=['' for i in range(9)]
COMBWI=['' for i in range(9)]
CONMAT=['' for i in range(9)]
CBLTYP=['' for i in range(9)]
CONVAR=['' for i in range(9)]
TCEPOX=['' for i in range(9)]

ZTRANS=0
YDELIV=0
MDELIV=0
TREVAL=0
CIMPT=0
CPUPT=0
CPUFN=0
CPUIND=0
CPUFIX=0
EXTRAR=[0 for i in range(9)]

MNLCOD=''
OPERAT=''
DETPRE=''
IDENT=''
PKLCOD=''
OPTLYR=['' for i in range(9)]
OPTTRN=['' for i in range(9)]
OPTCLD=['' for i in range(9)]
CAL009="0"

RWILI=0
CALCT=0
OFFIN=[0 for i in range(9)]
OFFOUT=[0 for i in range(9)]
DSPOOL=[0 for i in range(9)]
NLAYER=[0 for i in range(9)]
NTURNS=[0 for i in range(9)]
HCLAC=[0 for i in range(9)]

BOOSMA=0 
BOOSVO= 0
BOOSRE= 0
BOOSTR= 0
BBBOOS=0
TEMPLO= 0
STACKF= 0
SPFADU=0

FLPLMA=0

LAMTH=0 
LAMSPF=0 
LAMMW= 0
LAMOVL= 0
ACCLON= 0
ACCTRA=0
ACCVER= 0
AMBTEM= 0
LAMSTP= 0
LOSCOR= 0
TA1HOL=0

NCOOLI=0
