PI=3.1415927
def GOTO_39(DWIND,KWITYP,NWOLI,DUCTI,WWIND,RJH,I,ISAM,RLH,ZWIND,
            RGUID,HPART,TCOV1,TCOV2,RNCOOL,TCLT,HSPOL,HCLAC,ZLAG,
            ZCOIAR,PCSNED,ACOND,BPART,RPRTRR):
    #global DWIND,WWIND,DUCTI,RJH,KWITYP,I,NWOLI,ISAM,RGUID,RAAPN,WDUCT,HPART,TCOV1,TCOV2
    import common as CM
    PI=3.1415927
     #STANDARD VALUES USED BELOW:
#      NUMBER OF CLACK ROWS:
    PCLACK = DWIND * 0.024737
#             THIS WILL GIVE 30 % CLACK COVERAGE WITH CLACK WIDTH 38 MM
#      CLACK WIDTH (MM):
    WCLACK = 38
#      PRESSPAHN DENSITY (KG/MM3):
    RAAPN=1.22E-6
#      DUCT INSIDE WINDING AGAINST THE  FORMER CYLINDER (MM):
    WDUCT= 11
#     CLACK PITCH FOR INNER COOLING DUCTS (MM):
    PCLBD= 50
#      WIDTH OF RIBS IN MAIN DUCT (MM):
    RIBB = 20
#      THICKNESS OF FORMER CYLINDER (MM):
    TFOCY= 3
#      MEAN CIRCUMFERENCE OF FORMER CYLINDER (MM):
    WFOCY=(DWIND-WWIND-WDUCT*2-TFOCY)*PI
#      NUMBER OF SPLIT CYLINDERS INSIDE THE WINDING:
    RCYL= (DUCTI-WDUCT)/14 -1
    if(RCYL < 0): RCYL = 0
#      HEIGHT OF THE FORMER CYLINDER (MM):
    HFOCY= RJH - 6
#-----------------------------------------------------------------------
####   INSULATION DETAILS IN THE MAIN DUCT
####   SEPARATE WINDING PRODUCTION
    if(KWITYP == 1 or 2 or 3 or 4 or 5 or 6 or 7 ):
        CM.GSN131[I-1]=RAAPN*HFOCY*(WDUCT*PCLACK*RIBB+TFOCY*WFOCY)*NWOLI
        #MASS OF INSULATION DETAILS IN THE MAIN DUCT FOR "ACTIVE PART"
#****   -OR- IN CASE COMBINED WINDING PRODUCTION, ADD TO INSULATION
#****   DETAILS IN MAIN DUCT.
        HELP1= RAAPN*NWOLI*HFOCY
        HELP2= HELP1*RIBB *(DUCTI-TFOCY-WDUCT-RCYL)*PCLACK
        if(HELP2 < 0): HELP2=0
        HELP3= HELP1*PI*RCYL *(DWIND-DUCTI)

        CM.GSN41[I-1]= 0
        if(ISAM==1): CM.GSN41[I-1]= HELP2 + HELP3
        if(ISAM==2): CM.GSN131[I-1]= CM.GSN131[I-1] + HELP2 + HELP3
        GOTO_49(KWITYP,NWOLI,WDUCT,WWIND,DWIND,RJH,RLH,I,ZWIND,RGUID,RAAPN,HPART,TCOV1\
    ,TCOV2,RNCOOL,TCLT,HSPOL,HCLAC,ZLAG,ZCOIAR,WCLACK,PCLACK,PCSNED,ACOND,BPART,RPRTRR,PCLBD)
        

    if(KWITYP == 8):
        # FOIL WINDING: PLASTIC TUBE AND EPOXY
#*.... X1 = TUBE LENGTH .....
        X1 = (DWIND-WWIND-DUCTI)*PI*RLH/200.
        CM.GSN131[I-1] =(( X1*DUCTI*50 + 3.E6)*1.65E-6 + (X1+2000)*0.37E-3)*NWOLI

#*     FORMER CYLINDER FOR FOIL WINDING
        CM.GN1352[I-1] = RAAPN*HFOCY*TFOCY*WFOCY*NWOLI
        GOTO_49(KWITYP,NWOLI,WDUCT,WWIND,DWIND,RJH,RLH,I,ZWIND,RGUID,RAAPN,HPART,TCOV1\
    ,TCOV2,RNCOOL,TCLT,HSPOL,HCLAC,ZLAG,ZCOIAR,WCLACK,PCLACK,PCSNED,ACOND,BPART,RPRTRR,PCLBD,)

    if(KWITYP==9):
        # MULTI LAYER WINDING
        CM.GSN41[I-1] = 0.
        CM.GSN131[I-1]=PI*RAAPN*0.4*DUCTI*RLH*NWOLI*(DWIND-WWIND-DUCTI)
#                 .... SPACE FACTOR = 0.4 ........
        GOTO_49(KWITYP,NWOLI,WDUCT,WWIND,DWIND,RJH,RLH,I,ZWIND,RGUID,RAAPN,HPART,TCOV1\
    ,TCOV2,RNCOOL,TCLT,HSPOL,HCLAC,ZLAG,ZCOIAR,WCLACK,PCLACK,PCSNED,ACOND,BPART,RPRTRR,PCLBD,)

def GOTO_49(KWITYP,NWOLI,WDUCT,WWIND,DWIND,RJH,RLH,I,ZWIND,RGUID,RAAPN,HPART,TCOV1\
    ,TCOV2,RNCOOL,TCLT,HSPOL,HCLAC,ZLAG,ZCOIAR,WCLACK,PCLACK,PCSNED,ACOND,BPART,RPRTRR,PCLBD):
    #global DWIND,WWIND,DUCTI,RJH,KWITYP,I,NWOLI,ISAM,RGUID,RAAPN,WDUCT,HPART,TCOV1,TCOV2,RLH,ZWIND
    import common as CM
#INSULATION DETAILS AGAINST THE YOKES:

    if(KWITYP==1):
     #   SCREW:
        CM.GSN132[I-1]= 95.E-7*NWOLI*WDUCT**(-0.3)*WWIND*DWIND*((RJH-RLH)+(RLH/(ZWIND+1)))
        GOTO_80(I,RGUID,KWITYP,RAAPN,WDUCT,DWIND,HPART,TCOV1,TCOV2,NWOLI,RNCOOL,RLH,TCLT,HSPOL,HCLAC,\
    ZLAG,ZCOIAR,WCLACK,WWIND,PCLACK,PCSNED,RJH,ZWIND,ACOND,BPART,RPRTRR,PCLBD)

    if(KWITYP==2 or 3 or 7):
      #  LAYER, SERIES-LOOP  OR SERIES-LOOP SCREW WINDING
        CM.GSN132[I-1]=395.E-8*NWOLI*WWIND*DWIND*((RJH-RLH) +(RLH/(ZWIND+1)))
        GOTO_80(I,RGUID,KWITYP,RAAPN,WDUCT,DWIND,HPART,TCOV1,TCOV2,NWOLI,RNCOOL,RLH,TCLT,HSPOL,HCLAC,\
    ZLAG,ZCOIAR,WCLACK,WWIND,PCLACK,PCSNED,RJH,ZWIND,ACOND,BPART,RPRTRR,PCLBD)

    if(KWITYP== 3 or 4 or 5 or 8 or 9 or 10):
       # CONT.DISC, STAB. DISC, DISC-TWO, FOIL OR  MULTI-LAYER
        CM.GSN132[I-1]= 102.E-8*NWOLI*WDUCT**0.2*WWIND*DWIND*(RJH-RLH)
        GOTO_80(I,RGUID,KWITYP,RAAPN,WDUCT,DWIND,HPART,TCOV1,TCOV2,NWOLI,RNCOOL,RLH,TCLT,HSPOL,HCLAC,\
    ZLAG,ZCOIAR,WCLACK,WWIND,PCLACK,PCSNED,RJH,ZWIND,ACOND,BPART,RPRTRR,PCLBD)

def GOTO_80(I,RGUID,KWITYP,RAAPN,WDUCT,DWIND,HPART,TCOV1,TCOV2,NWOLI,RNCOOL,RLH,TCLT,HSPOL,HCLAC,\
    ZLAG,ZCOIAR,WCLACK,WWIND,PCLACK,PCSNED,RJH,ZWIND,ACOND,BPART,RPRTRR,PCLBD):
    
    import common as CM
   # OIL-GUIDING RINGS
    CM.GSN133[I-1]=0
    if(RGUID > 1 and KWITYP <=7):
        CM.GSN133[I-1]=RAAPN* PI*WDUCT*DWIND*(HPART+TCOV1+TCOV2)*RGUID*NWOLI

    #CLACK BAND FOR INNER COOLING DUCTS
    if(KWITYP<=7):
        CM.GSN134[I-1]=NWOLI*DWIND*PI*RNCOOL*(RLH-TCLT)**(1.10E-4/PCLBD + 2.5E-7)

    # FOIL AND MULTI-LAYER WINDINGS
    if(KWITYP >= 8):
        CM.GSN134[I-1]= NWOLI*DWIND*PI*RNCOOL*RLH*NWOLI*1.2*RAAPN
        # .... SPACEFACTOR 0.4  * THICKNESS 3 MM   GIVES 1.2 .....
    if(KWITYP ==9):
        #LAYER INSULATION IN LNX-WINDINGS:
        CM.GN1351[I-1] = DWIND*PI*(HSPOL+50.)*HCLAC*1.11*(ZLAG+1)*ZCOIAR*1.E-6*NWOLI
        #.... DENSITY 1.01 G/CM3, OVER-LAP 1.10  GIVES 1.11 .....

    if(not(KWITYP>7)):
      #  CLACKS
        GSN135= RAAPN*WCLACK*TCLT*NWOLI*WWIND*PCLACK
        CM.GN1352[I-1] = PCSNED/100.* GSN135
        CM.GN1351[I-1] = GSN135 - CM.GN1352[I-1]

     #LOCKING CYLINDERS
    CM.GSN136[I-1] =0 
    if(WWIND <= 9.5 and KWITYP <=7):
        CM.GSN136[I-1] = 0
        return 

    if(KWITYP == 1 or 3 or 4 or 5 or 8):
        CM.GSN136[I-1] = 0
        return 
    if(KWITYP == 2 or 6 or 7):
        CM.GSN136[I-1] = 1.95E-5*NWOLI*(DWIND+WWIND+5.)*(RJH-RLH+3.*RLH/(ZWIND+1))
        return 
    if(KWITYP==9):
        CM.GSN136[I-1]= ZLAG*DWIND*PI*1.2E-6*(26.+ ACOND/BPART/RPRTRR)*ZCOIAR*NWOLI
        return 




def MASS02(BBPRNT,JFC,I,DCORE,HLIMB,RLH,RJH,KWITYP,PLIMB,\
    ACOND,RAACON,NCOND,NWOLI,HPART,BPART,RPRTAR,\
    RPRTRR,\
    TCOV1,TCOV2,ZLOOP,ZWIND,DWIND,WWIND,DUCTI,ISAM,\
    TCLT,RGUID,RNCOOL,PCSNED,HSPOL,HCLAC,ZLAG,\
    ZCOIAR,NGROUP,IPISOL):
    import common as CM
    #global DWIND,WWIND,DUCTI,RJH,KWITYP,I,NWOLI,ISAM,RGUID,RAAPN,WDUCT,HPART,TCOV1,TCOV2,RLH
    #DECLARATIONS
    
    PI=3.1415927
    
    if(BBPRNT): 
        #PMASS2(BBPRNT,6,I,DCORE,HLIMB,RLH,RJH,KWITYP,PLIMB,\
#ACOND,RAACON,NCOND,NWOLI,HPART,BPART,RPRTAR,\
#RPRTRR,\
#TCOV1,TCOV2,ZLOOP,ZWIND,DWIND,WWIND,DUCTI,ISAM,\
#TCLT,RGUID,RNCOOL,PCSNED,HSPOL,HCLAC,ZLAG,\
#ZCOIAR,NGROUP,IPISOL)
        pass

    ZLOOPX=1
    if(ZLOOP>0): ZLOOPX=ZLOOP
    # CONDUCTOR NET MASS INCLUDING ADDITIONS FOR START AND
#****   FINISH OF THE WINDING.
#*      ADD  1.5 % OF THE TOTAL LENGTH, BUT NEVER LESS THAN 2500 MM.
#*      ADD FOR DISC-TWO WINDINGS: (LIMB PITCH)/4 + 200   MM.


    CM.GSN11[I-1]= PI*1.E-6*DWIND * ZWIND *ACOND*RAACON*NWOLI
    PLUS1 = 0.015 * CM.GSN11[I-1]
    PLUS2 = 2500
    PLUS2= PLUS2*(1.E-6 * ACOND * RAACON * NWOLI * ZLOOPX)
    CM.GSN11[I-1]= CM.GSN11[I-1] + max(PLUS1,PLUS2)
#*
#*-----------------------------------------------------------------------
#****   PAPER COVERING

    CM.GSN121[I-1] = 0.
    CM.GSN122[I-1] = 0.

    
    if(NCOND==3): GOTO_39(DWIND,KWITYP,NWOLI,DUCTI,WWIND,RJH,I,ISAM,RLH,ZWIND,RGUID,HPART,TCOV1,TCOV2,RNCOOL,\
    TCLT,HSPOL,HCLAC,ZLAG,ZCOIAR,PCSNED,ACOND,BPART,RPRTRR)
    # CALCULATE TOTAL CABLE LENGTH
    CBLLNG = CM.GSN11[I-1]/HPART/BPART/RPRTAR/RPRTRR/RAACON

   #    ASSIGN DENSITIES FOR DIFFERENT COVERING (KG/DM3)
#CC*KOM
#CC*    RAASP #NDR FR .375 T .75 (VERKLIGT V#RDE)
#CC*    TIDIGARE MULT. MED 2 I MASS BER#KN TAS BORT
#CC*
    RAASP = 0.750
    RAAOR = 1.140
    RAALR = 1.167

    if(KWITYP==1 or 2 or 3 or 4 or 5 or 6 or 7):
        if(IPISOL==1):
            #PAPER ISOLATION
            CM.GSN121[I-1] = (HPART+BPART+TCOV1)*RPRTAR*RPRTRR*CBLLNG*TCOV1*RAASP
            CM.GSN122[I-1] = (RPRTAR*(HPART+TCOV1)+RPRTRR*(BPART+TCOV1)+TCOV2)*CBLLNG*TCOV2*RAASP
            GOTO_39(DWIND,KWITYP,NWOLI,DUCTI,WWIND,RJH,I,ISAM,RLH,ZWIND,RGUID,HPART,TCOV1,TCOV2,RNCOOL,\
    TCLT,HSPOL,HCLAC,ZLAG,ZCOIAR,PCSNED,ACOND,BPART,RPRTRR)
            return
        if(IPISOL==2):
           #MYLAR PRESSPAHN
            CM.GSN121[I-1] = HPART*RPRTAR*(RPRTRR-1)*CBLLNG*TCOV1*RAAOR
            CM.GSN122[I-1] = (HPART*RPRTAR+BPART*RPRTRR+(RPRTRR-1)*TCOV1+TCOV2)*CBLLNG*TCOV2*RAASP
            GOTO_39(DWIND,KWITYP,NWOLI,DUCTI,WWIND,RJH,I,ISAM,RLH,ZWIND,RGUID,HPART,TCOV1,TCOV2,RNCOOL,\
    TCLT,HSPOL,HCLAC,ZLAG,ZCOIAR,PCSNED,ACOND,BPART,RPRTRR)
            return
        if(IPISOL==3):
            CM.GSN121[I-1] = HPART*RPRTAR*(RPRTRR-1)*CBLLNG*TCOV1*RAALR
            CM.GSN122[I-1] = (HPART*RPRTAR+BPART*RPRTRR+(RPRTRR-1)*TCOV1+TCOV2)*CBLLNG*TCOV2*RAASP
            GOTO_39(DWIND,KWITYP,NWOLI,DUCTI,WWIND,RJH,I,ISAM,RLH,ZWIND,RGUID,HPART,TCOV1,TCOV2,RNCOOL,\
    TCLT,HSPOL,HCLAC,ZLAG,ZCOIAR,PCSNED,ACOND,BPART,RPRTRR)
            return

    if(KWITYP==8):
       # FOIL WINDING
        CM.GSN121[I-1]= ((HPART+30.)*TCOV1 + BPART*30.)*ZWIND*DWIND*PI*NGROUP*NWOLI*1.1E-6
#*                 .... BPART*30. IS CROSS SECTION AREA OF EDGE FILLING...
        CM.GSN122[I-1] = 0
        GOTO_39(DWIND,KWITYP,NWOLI,DUCTI,WWIND,RJH,I,ISAM,RLH,ZWIND,RGUID,HPART,TCOV1,TCOV2,RNCOOL,\
    TCLT,HSPOL,HCLAC,ZLAG,ZCOIAR,PCSNED,ACOND,BPART,RPRTRR)
        return

    if(KWITYP==9):
        #MULTI LAYER WINDING
#*      INSULATION STRIPS BETWEEN STRANDS
        CM.GSN121[I-1] = (HPART+1.)*0.3*DWIND*PI*ZWIND*NGROUP*(RPRTRR-1.)*1.4E-6 * NWOLI
#*      PAPER COVERING CABLE (STRAND IF(RPRTRR = 1))
        HLPA= HPART
        HLPR= RPRTRR*(BPART+0.3) - 0.3
        CM.GSN122[I-1] = RAASP/RAACON*(TCOV2+HLPA+HLPR)*TCOV2/HLPA/HLPR*CM.GSN11[I-1]

