def SAMPLEPRINT():
    import com as C
    '''print('I/O CORE ROUTINE    ',C.TEXT[0] )
    print('CALC.IN LMIN        ',C.TEXT[1] )
    print('CALC.IN ADDAT       ',C.TEXT[2] )
    print('CYCLES IN LMIN      ',C.TEXT[3] )
    print('10 CYCL.IN LMIN     ',C.TEXT[4] )
    print('LINK CHANGES        ',C.TEXT[6] )
    print('CALL FROM INPUT     ',C.TEXT[7] )
    print('CALL FROM FUNK      ',C.TEXT[8] )
    print('MASS/COST 6         ',C.TEXT[9] )'''
    print('Number of phases    ',C.IARR[0] )
    print('Trnsp.prof. code    ',C.IARR[1] )
    print('Max No of calcs.    ',C.IARR[2] )
    print('No.of + steps T1    ',C.IARR[5] )
    print('No.of + steps T2    ',C.IARR[6] )
    print('No.of + steps T3    ',C.IARR[7] )
    print('No.of - steps T1    ',C.IARR[10] )
    print('No.of - steps T2    ',C.IARR[11] )
    print('No.of - steps T3    ',C.IARR[12] )
    print('Term.connect. W1    ',C.IARR[20] )
    print('Term.connect. W2    ',C.IARR[21] )
    print('Term.connect. W3    ',C.IARR[22] )
    print('Term.connect. W4    ',C.IARR[23] )
    print('Term.connect. W5    ',C.IARR[24] )
    print('Term.connect. W6    ',C.IARR[25] )
    print('Term.connect. W7    ',C.IARR[26] )
    print('Term.connect. W8    ',C.IARR[27] )
    print('Term.connect. W9    ',C.IARR[28] )
    print('Function code W1    ',C.IARR[30] )
    print('Function code W2    ',C.IARR[31] )
    print('Function code W3    ',C.IARR[32] )
    print('Function code W4    ',C.IARR[33] )
    print('Function code W5    ',C.IARR[34] )
    print('Function code W6    ',C.IARR[35] )
    print('Function code W7    ',C.IARR[36] )
    print('Function code W8    ',C.IARR[37] )
    print('Function code W9    ',C.IARR[38] )
    print('No.Par.groups W1    ',C.IARR[40] )
    print('No.Par.groups W2    ',C.IARR[41] )
    print('No.Par.groups W3    ',C.IARR[42] )
    print('No.Par.groups W4    ',C.IARR[43] )
    print('No.Par.groups W5    ',C.IARR[44] )
    print('No.Par.groups W6    ',C.IARR[45] )
    print('No.Par.groups W7    ',C.IARR[46] )
    print('No.Par.groups W8    ',C.IARR[47] )
    print('No.Par.groups W9    ',C.IARR[48] )
    print('No. Wound limbs     ',C.IARR[50] )
    print('Tank type-code      ',C.IARR[52] )
    print('Reactance T 1-3     ',C.AARR[0] )
    print('Frequency (Hz)      ',C.AARR[1] )
    print('Reactance T 2-3     ',C.AARR[2] )
    print('Reactance T 1-2     ',C.AARR[3] )
    print('Overvoltage (%)     ',C.AARR[4] )
    print('Eval.Noload loss    ',C.AARR[5] )
    print('Eval.Load loss      ',C.AARR[6] )
    print('Eval.Sum loss       ',C.AARR[8] )
    print('Rated power T1      ',C.AARR[10] )
    print('Rated power T2      ',C.AARR[11] )
    print('Rated power T3      ',C.AARR[12] )
    print('Rated power T4      ',C.AARR[13] )
    print('Loss ratio          ',C.AARR[14] )
    print('Main voltage T1     ',C.AARR[15] )
    print('Main voltage T2     ',C.AARR[16] )
    print('Main voltage T3     ',C.AARR[17] )
    print('Main voltage T4     ',C.AARR[18] )
    print('Max comp.price      ',C.AARR[19] )
    print('Reg.volt.T1 (%)     ',C.AARR[20] )
    print('Reg.volt.T2 (%)     ',C.AARR[21] )
    print('Reg.volt.T3 (%)     ',C.AARR[22] )
    print('Product class       ',C.AARR[23] )
    print('Monthly Infl.(%)    ',C.AARR[24] )
    print('Impulse volt. T1    ',C.AARR[25] )
    print('Impulse volt. T2    ',C.AARR[26] )
    print('Impulse volt. T3    ',C.AARR[27] )
    print('Impulse volt. T4    ',C.AARR[28] )
    print('Trnsp.dist in SW    ',C.AARR[29] )
    print('Scpower T1 (GVA)    ',C.AARR[30] )
    print('Scpower T2 (GVA)    ',C.AARR[31] )
    print('Scpower T3 (GVA)    ',C.AARR[32] )
    print('Loss Scale fact     ',C.AARR[33] )
    print('Cost Scale fact     ',C.AARR[34] )
    print('Int.reactor (%)     ',C.AARR[35] )
    print('Int.reactor (%)     ',C.AARR[36] )
    print('Int.reactor (%)     ',C.AARR[37] )
    print('K1 in PT calc.      ',C.AARR[38] )
    print('K2 in PT calc.      ',C.AARR[39] )
    print('Fraction W1 (pu)    ',C.AARR[40] )
    print('Fraction W2 (pu)    ',C.AARR[41] )
    print('Fraction W3 (pu)    ',C.AARR[42] )
    print('Fraction W4 (pu)    ',C.AARR[43] )
    print('Fraction W5 (pu)    ',C.AARR[44] )
    print('Fraction W6 (pu)    ',C.AARR[45] )
    print('Fraction W7 (pu)    ',C.AARR[46] )
    print('Fraction W8 (pu)    ',C.AARR[47] )
    print('Fraction W9 (pu)    ',C.AARR[48] )
    print('Current dens. W1    ',C.AARR[50] )
    print('Current dens. W2    ',C.AARR[51] )
    print('Current dens. W3    ',C.AARR[52] )
    print('Current dens. W4    ',C.AARR[53] )
    print('Current dens. W5    ',C.AARR[54] )
    print('Current dens. W6    ',C.AARR[55] )
    print('Current dens. W7    ',C.AARR[56] )
    print('Current dens. W8    ',C.AARR[57] )
    print('Current dens. W9    ',C.AARR[58] )
    print('Mass-factor         ',C.AARR[59] )
    print('Conduct area W1     ',C.AARR[60] )
    print('Conduct area W2     ',C.AARR[61] )
    print('Conduct area W3     ',C.AARR[62] )
    print('Conduct area W4     ',C.AARR[63] )
    print('Conduct area W5     ',C.AARR[64] )
    print('Conduct area W6     ',C.AARR[65] )
    print('Conduct area W7     ',C.AARR[66] )
    print('Conduct area W8     ',C.AARR[67] )
    print('Conduct area W9     ',C.AARR[68] )
    print('Main duct ins.W1    ',C.AARR[70] )
    print('Main duct ins.W2    ',C.AARR[71] )
    print('Main duct ins.W3    ',C.AARR[72] )
    print('Main duct ins.W4    ',C.AARR[73] )
    print('Main duct ins.W5    ',C.AARR[74] )
    print('Main duct ins.W6    ',C.AARR[75] )
    print('Main duct ins.W7    ',C.AARR[76] )
    print('Main duct ins.W8    ',C.AARR[77] )
    print('Main duct ins.W9    ',C.AARR[78] )
    print('Fillf.n.ext.varn    ',C.AARR[79] )
    print('Space factor W1     ',C.AARR[80] )
    print('Space factor W2     ',C.AARR[81] )
    print('Space factor W3     ',C.AARR[82] )
    print('Space factor W4     ',C.AARR[83] )
    print('Space factor W5     ',C.AARR[84] )
    print('Space factor W6     ',C.AARR[85] )
    print('Space factor W7     ',C.AARR[86] )
    print('Space factor W8     ',C.AARR[87] )
    print('Space factor W9     ',C.AARR[88] )
    print('Fillf.ext.varn      ',C.AARR[89] )
    print('Winding width W1    ',C.AARR[90] )
    print('Winding width W2    ',C.AARR[91] )
    print('Winding width W3    ',C.AARR[92] )
    print('Winding width W4    ',C.AARR[93] )
    print('Winding width W5    ',C.AARR[94] )
    print('Winding width W6    ',C.AARR[95] )
    print('Winding width W7    ',C.AARR[96] )
    print('Winding width W8    ',C.AARR[97] )
    print('Winding width W9    ',C.AARR[98] )
    print('Temprise topoil     ',C.AARR[99] )
    print('Yoke-distance W1    ',C.AARR[100] )
    print('Yoke-distance W2    ',C.AARR[101] )
    print('Yoke-distance W3    ',C.AARR[102] )
    print('Yoke-distance W4    ',C.AARR[103] )
    print('Yoke-distance W5    ',C.AARR[104] )
    print('Yoke-distance W6    ',C.AARR[105] )
    print('Yoke-distance W7    ',C.AARR[106] )
    print('Yoke-distance W8    ',C.AARR[107] )
    print('Yoke-distance W9    ',C.AARR[108] )
    print('Temprise MO ONAN    ',C.AARR[109] )
    print('Cond. width W1      ',C.AARR[110] )
    print('Cond. width W2      ',C.AARR[111] )
    print('Cond. width W3      ',C.AARR[112] )
    print('Cond. width W4      ',C.AARR[113] )
    print('Cond. width W5      ',C.AARR[114] )
    print('Cond. width W6      ',C.AARR[115] )
    print('Cond. width W7      ',C.AARR[116] )
    print('Cond. width W8      ',C.AARR[117] )
    print('Cond. width W9      ',C.AARR[118] )
    print('Temprise MO ONAF    ',C.AARR[119] )
    print('Tens.stress W1      ',C.AARR[120] )
    print('Tens.stress W2      ',C.AARR[121] )
    print('Tens.stress W3      ',C.AARR[122] )
    print('Tens.stress W4      ',C.AARR[123] )
    print('Tens.stress W5      ',C.AARR[124] )
    print('Tens.stress W6      ',C.AARR[125] )
    print('Tens.stress W7      ',C.AARR[126] )
    print('Tens.stress W8      ',C.AARR[127] )
    print('Tens.stress W9      ',C.AARR[128] )
    print('Temprise MO OFAF    ',C.AARR[129] )
    print('Max. Press. W1      ',C.AARR[130] )
    print('Max. Press. W2      ',C.AARR[131] )
    print('Max. Press. W3      ',C.AARR[132] )
    print('Max. Press. W4      ',C.AARR[133] )
    print('Max. Press. W5      ',C.AARR[134] )
    print('Max. Press. W6      ',C.AARR[135] )
    print('Max. Press. W7      ',C.AARR[136] )
    print('Max. Press. W8      ',C.AARR[137] )
    print('Max. Press. W9      ',C.AARR[138] )
    print('Core blading        ',C.AARR[139] )
    print('Dist.betw.phases    ',C.AARR[140] )
    print('Dist.to.sidelimb    ',C.AARR[141] )
    print('Core diameter       ',C.AARR[142] )
    print('Turn-voltage        ',C.AARR[144] )
    print('Flux density        ',C.AARR[145] )
    print('Max.flux density    ',C.AARR[146] )
    print('Yokeht.incr.TCA     ',C.AARR[149] )
    print('Dist.wind.-tank     ',C.AARR[150] )
    print('Extens. of tank     ',C.AARR[151] )
    print('Dist.core-cover     ',C.AARR[152] )
    print('Self-cool.ratio     ',C.AARR[153] )
    print('Max.windtemprise    ',C.AARR[154] )
    print('Max.TO.temprise     ',C.AARR[155] )
    print('Yokeht .red. TBA    ',C.AARR[159] )
    print('Re-opt.index(%)     ',C.AARR[160] )
    print('Fixed Price (%)     ',C.AARR[167] )
    print('Min.Core diam.      ',C.AARR[169] )
    print('Max.Core diam.      ',C.AARR[170] )
    print('Max.Trnsp.mass      ',C.AARR[172] )
    print('Max.tank height     ',C.AARR[173] )
    print('Max,tank width      ',C.AARR[174] )
    print('Max.tank length     ',C.AARR[175] )
    print('Max.sound level     ',C.AARR[176] )
    print('Core-steel          ',C.TARR[0] )
    print('Var.flux regul.     ',C.TARR[1] )
    print('Highcond.Fld.Scr    ',C.TARR[2] )
    print('Dshell H.cur.wdg    ',C.TARR[3] )
    print('Regulation T1       ',C.TARR[5] )
    print('Regulation T2       ',C.TARR[6] )
    print('Regulation T3       ',C.TARR[7] )
    print('Type of regul.T1    ',C.TARR[10] )
    print('Type of regul.T2    ',C.TARR[11] )
    print('Type of regul.T3    ',C.TARR[12] )
    print('Connection T1       ',C.TARR[20] )
    print('Connection T2       ',C.TARR[21] )
    print('Connection T3       ',C.TARR[22] )
    print('Connection T4       ',C.TARR[23] )
    print('Winding type W1     ',C.TARR[30] )
    print('Winding type W2     ',C.TARR[31] )
    print('Winding type W3     ',C.TARR[32] )
    print('Winding type W4     ',C.TARR[33] )
    print('Winding type W5     ',C.TARR[34] )
    print('Winding type W6     ',C.TARR[35] )
    print('Winding type W7     ',C.TARR[36] )
    print('Winding type W8     ',C.TARR[37] )
    print('Winding type W9     ',C.TARR[38] )
    print('Cond.material W1    ',C.TARR[40] )
    print('Cond.material W2    ',C.TARR[41] )
    print('Cond.material W3    ',C.TARR[42] )
    print('Cond.material W4    ',C.TARR[43] )
    print('Cond.material W5    ',C.TARR[44] )
    print('Cond.material W6    ',C.TARR[45] )
    print('Cond.material W7    ',C.TARR[46] )
    print('Cond.material W8    ',C.TARR[47] )
    print('Cond.material W9    ',C.TARR[48] )
    print('Side limb (Y/N)     ',C.TARR[50] )
    print('Type of cooling     ',C.TARR[55] )
    print('Type of cable W1    ',C.TARR[60] )
    print('Type of cable W2    ',C.TARR[61] )
    print('Type of cable W3    ',C.TARR[62] )
    print('Type of cable W4    ',C.TARR[63] )
    print('Type of cable W5    ',C.TARR[64] )
    print('Type of cable W6    ',C.TARR[65] )
    print('Type of cable W7    ',C.TARR[66] )
    print('Type of cable W8    ',C.TARR[67] )
    print('Type of cable W9    ',C.TARR[68] )
    print('Tank mass stated    ',C.TARR[72] )
    print('Sound screens       ',C.TARR[74] )
    print('Detailed precalc    ',C.TARR[77] )
    print('Core-banding        ',C.TARR[79] )
    print('TAD cooling calc    ',C.TARR[81] )
    print('Dshell H.cur.wdg    ',C.TARR[94] )
    print('No.cool.ducts W1    ',C.BARR[0] )
    print('No.cool.ducts W2    ',C.BARR[1] )
    print('No.cool.ducts W3    ',C.BARR[2] )
    print('No.cool.ducts W4    ',C.BARR[3] )
    print('No.cool.ducts W5    ',C.BARR[4] )
    print('No.cool.ducts W6    ',C.BARR[5] )
    print('No.cool.ducts W7    ',C.BARR[6] )
    print('No.cool.ducts W8    ',C.BARR[7] )
    print('No.cool.ducts W9    ',C.BARR[8] )
    print('Cond.height W1      ',C.BARR[10] )
    print('Cond.height W2      ',C.BARR[11] )
    print('Cond.height W3      ',C.BARR[12] )
    print('Cond.height W4      ',C.BARR[13] )
    print('Cond.height W5      ',C.BARR[14] )
    print('Cond.height W6      ',C.BARR[15] )
    print('Cond.height W7      ',C.BARR[16] )
    print('Cond.height W8      ',C.BARR[17] )
    print('Cond.height W9      ',C.BARR[18] )
    print('Tot.paper cov.W1    ',C.BARR[20] )
    print('Tot.paper cov.W2    ',C.BARR[21] )
    print('Tot.paper cov.W3    ',C.BARR[22] )
    print('Tot.paper cov.W4    ',C.BARR[23] )
    print('Tot.paper cov.W5    ',C.BARR[24] )
    print('Tot.paper cov.W6    ',C.BARR[25] )
    print('Tot.paper cov.W7    ',C.BARR[26] )
    print('Tot.paper cov.W8    ',C.BARR[27] )
    print('Tot.paper cov.W9    ',C.BARR[28] )
    print('Winding support     ',C.BARR[29] )
    print('Assembly press      ',C.BARR[30] )
    print('EPS  Opt.const      ',C.BARR[31] )
    print('FEPS Opt.const      ',C.BARR[32] )
    print('DRV  Opt.const      ',C.BARR[33] )
    print('AF   Opt.const      ',C.BARR[34] )
    print('P(3) Opt.const      ',C.BARR[35] )
    print('P(13)Opt.const      ',C.BARR[36] )
    print('Comb.wdg.prod W1    ',C.UARR[0] )
    print('Comb.wdg.prod W2    ',C.UARR[1] )
    print('Comb.wdg.prod W3    ',C.UARR[2] )
    print('Comb.wdg.prod W4    ',C.UARR[3] )
    print('Comb.wdg.prod W5    ',C.UARR[4] )
    print('Comb.wdg.prod W6    ',C.UARR[5] )
    print('Comb.wdg.prod W7    ',C.UARR[6] )
    print('Comb.wdg.prod W8    ',C.UARR[7] )
    print('Comb.wdg.prod W9    ',C.UARR[8] )
    print('Transp.cable W1     ',C.UARR[10] )
    print('Transp.cable W2     ',C.UARR[11] )
    print('Transp.cable W3     ',C.UARR[12] )
    print('Transp.cable W4     ',C.UARR[13] )
    print('Transp.cable W5     ',C.UARR[14] )
    print('Transp.cable W6     ',C.UARR[15] )
    print('Transp.cable W7     ',C.UARR[16] )
    print('Transp.cable W8     ',C.UARR[17] )
    print('Transp.cable W9     ',C.UARR[18] )
    print('Optimise tank       ',C.UARR[19] )
    print('Core type           ',C.UARR[21] )
    print('Step Lap core       ',C.UARR[22] )
    print('Varnish copper W1   ',C.UARR[30] )
    print('Varnish copper W2   ',C.UARR[31] )
    print('Varnish copper W3   ',C.UARR[32] )
    print('Varnish copper W4   ',C.UARR[33] )
    print('Varnish copper W5   ',C.UARR[34] )
    print('Varnish copper W6   ',C.UARR[35] )
    print('Varnish copper W7   ',C.UARR[36] )
    print('Varnish copper W8   ',C.UARR[37] )
    print('Varnish copper W9   ',C.UARR[38] )
    print('Epoxy glue on TC W1 ',C.UARR[40] )
    print('Epoxy glue on TC W2 ',C.UARR[41] )
    print('Epoxy glue on TC W3 ',C.UARR[42] )
    print('Epoxy glue on TC W4 ',C.UARR[43] )
    print('Epoxy glue on TC W5 ',C.UARR[44] )
    print('Epoxy glue on TC W6 ',C.UARR[45] )
    print('Epoxy glue on TC W7 ',C.UARR[46] )
    print('Epoxy glue on TC W8 ',C.UARR[47] )
    print('Epoxy glue on TC W9 ',C.UARR[48] )
    print('No.guid.rings W1    ',C.DARR[0] )
    print('No.guid.rings W2    ',C.DARR[1] )
    print('No.guid.rings W3    ',C.DARR[2] )
    print('No.guid.rings W4    ',C.DARR[3] )
    print('No.guid.rings W5    ',C.DARR[4] )
    print('No.guid.rings W6    ',C.DARR[5] )
    print('No.guid.rings W7    ',C.DARR[6] )
    print('No.guid.rings W8    ',C.DARR[7] )
    print('No.guid.rings W9    ',C.DARR[8] )
    print('Max.limb height     ',C.DARR[9] )
    print('Tapered clack W1    ',C.DARR[10] )
    print('Tapered clack W2    ',C.DARR[11] )
    print('Tapered clack W3    ',C.DARR[12] )
    print('Tapered clack W4    ',C.DARR[13] )
    print('Tapered clack W5    ',C.DARR[14] )
    print('Tapered clack W6    ',C.DARR[15] )
    print('Tapered clack W7    ',C.DARR[16] )
    print('Tapered clack W8    ',C.DARR[17] )
    print('Tapered clack W9    ',C.DARR[18] )
    print('Limb height         ',C.DARR[19] )
    print('Strands/cable W1    ',C.DARR[20] )
    print('Strands/cable W2    ',C.DARR[21] )
    print('Strands/cable W3    ',C.DARR[22] )
    print('Strands/cable W4    ',C.DARR[23] )
    print('Strands/cable W5    ',C.DARR[24] )
    print('Strands/cable W6    ',C.DARR[25] )
    print('Strands/cable W7    ',C.DARR[26] )
    print('Strands/cable W8    ',C.DARR[27] )
    print('Strands/cable W9    ',C.DARR[28] )
    print('Core-varnishing     ',C.DARR[29] )
    print('Cover,strand W1     ',C.DARR[30] )
    print('Cover,strand W2     ',C.DARR[31] )
    print('Cover,strand W3     ',C.DARR[32] )
    print('Cover,strand W4     ',C.DARR[33] )
    print('Cover,strand W5     ',C.DARR[34] )
    print('Cover,strand W6     ',C.DARR[35] )
    print('Cover,strand W7     ',C.DARR[36] )
    print('Cover,strand W8     ',C.DARR[37] )
    print('Cover,strand W9     ',C.DARR[38] )
    print('Min.limb height     ',C.DARR[39] )
    print('Extra Ax.ins W1     ',C.DARR[40] )
    print('Extra Ax.ins W2     ',C.DARR[41] )
    print('Extra Ax.ins W3     ',C.DARR[42] )
    print('Extra Ax.ins W4     ',C.DARR[43] )
    print('Extra Ax.ins W5     ',C.DARR[44] )
    print('Extra Ax.ins W6     ',C.DARR[45] )
    print('Extra Ax.ins W7     ',C.DARR[46] )
    print('Extra Ax.ins W8     ',C.DARR[47] )
    print('Extra Ax.ins W9     ',C.DARR[48] )
    print('Clack height W1     ',C.DARR[50] )
    print('Clack height W2     ',C.DARR[51] )
    print('Clack height W3     ',C.DARR[52] )
    print('Clack height W4     ',C.DARR[53] )
    print('Clack height W5     ',C.DARR[54] )
    print('Clack height W6     ',C.DARR[55] )
    print('Clack height W7     ',C.DARR[56] )
    print('Clack height W8     ',C.DARR[57] )
    print('Clack height W9     ',C.DARR[58] )
